---
# task file for initialising and updating databse if configured

- name: Check Kea DHCP database version # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: "/usr/sbin/kea-admin db-version {{ kea_dhcp_database_config.type }}\
          {% if 'user' in kea_dhcp_database_config %} -u {{ kea_dhcp_database_config.user }}{% endif %}\
          {% if 'database' in kea_dhcp_database_config %} -n {{ kea_dhcp_database_config.database }}{% endif %}\
          {% if 'password' in kea_dhcp_database_config %} -p {{ kea_dhcp_database_config.password }}{% endif %}\
          {% if 'port' in kea_dhcp_database_config %} -P {{ kea_dhcp_database_config.port }}{% endif %}\
          {% if 'host' in kea_dhcp_database_config %} -h {{ kea_dhcp_database_config.host }}{% endif %}"
  register: kea_dhcp_db_version
  changed_when: false
  ignore_errors: true
  no_log: true

- name: Initialise Kea DHCP database # noqa: no-changed-when command-instead-of-shell
  ansible.builtin.shell:
    cmd: "/usr/sbin/kea-admin db-init {{ kea_dhcp_database_config.type }}\
          {% if 'user' in kea_dhcp_database_config %} -u {{ kea_dhcp_database_config.user }}{% endif %}\
          {% if 'database' in kea_dhcp_database_config %} -n {{ kea_dhcp_database_config.database }}{% endif %}\
          {% if 'password' in kea_dhcp_database_config %} -p {{ kea_dhcp_database_config.password }}{% endif %}\
          {% if 'port' in kea_dhcp_database_config %} -P {{ kea_dhcp_database_config.port }}{% endif %}\
          {% if 'host' in kea_dhcp_database_config %} -h {{ kea_dhcp_database_config.host }}{% endif %}"
  when: kea_dhcp_db_version is failed
  notify: restart kea-dhcp
  no_log: true
    
# Commented out because 1) doing an upgrade is dangerous 2) the datbase version doesn't match Kea version
# - name: Update Kea DHCP database # noqa: no-changed-when command-instead-of-shell
#   ansible.builtin.shell:
#     cmd: "/usr/sbin/kea-admin db-upgrade {{ kea_dhcp_database_config.type }}\
#           {% if 'user' in kea_dhcp_database_config %} -u {{ kea_dhcp_database_config.user }}{% endif %}\
#           {% if 'database' in kea_dhcp_database_config %} -n {{ kea_dhcp_database_config.database }}{% endif %}\
#           {% if 'password' in kea_dhcp_database_config %} -p {{ kea_dhcp_database_config.password }}{% endif %}\
#           {% if 'port' in kea_dhcp_database_config %} -P {{ kea_dhcp_database_config.port }}{% endif %}\
#           {% if 'host' in kea_dhcp_database_config %} -h {{ kea_dhcp_database_config.host }}{% endif %}"
#   when:
#     - kea_dhcp_db_version.stdout != kea_dhcp_version
#     - kea_dhcp_db_version is succeeded
#   notify: restart kea-dhcp
#   no_log: true
