---
- name: debian | updating apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: true
  register: result
  until: result is successful

- name: debian | installing kea packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  register: result
  until: result is successful
  with_items: "{{ kea_dhcp_debian_packages }}"
