---
# tasks file for ansible-kea-dhcp
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: services.yml

- include_tasks: config.yml
