---
- name: services | enabling kea services
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items: '{{ kea_dhcp_services }}'

- name: services | ensuring kea services are started
  service:
    name: "{{ item.name }}"
    state: "started"
  with_items: '{{ kea_dhcp_services }}'
  when: item.enabled
