---
- name: services | enabling kea services (Debian)
  service:
    name: "{{ item['name'] }}"
    enabled: "{{ item['enabled'] }}"
  become: true
  loop: "{{ kea_dhcp_debian_services }}"
  when:
    - ansible_os_family == "Debian"
    - item['enabled']|bool

- name: services | ensuring kea services are started (Debian)
  service:
    name: "{{ item['name'] }}"
    state: started
  become: true
  loop: "{{ kea_dhcp_debian_services }}"
  when:
    - ansible_os_family == "Debian"
    - item['enabled']|bool

- name: services | enabling kea services (RedHat)
  service:
    name: "{{ item['name'] }}"
    enabled: "{{ item['enabled'] }}"
  become: true
  loop: "{{ kea_dhcp_redhat_services }}"
  when:
    - ansible_os_family == "RedHat"
    - item['enabled']|bool

- name: services | ensuring kea services are started (RedHat)
  service:
    name: "{{ item['name'] }}"
    state: started
  become: true
  loop: "{{ kea_dhcp_redhat_services }}"
  when:
    - ansible_os_family == "RedHat"
    - item['enabled']|bool
